server:
  port: 8080


spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html



  datasource:
    druid:
      driver-class-name: ${shsl.datasource.driver-class-name}
      url: jdbc:mysql://${shsl.datasource.host}:${shsl.datasource.port}/${shsl.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      userName: ${shsl.datasource.userName}
      password: ${shsl.datasource.password}



mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shsl.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      shsl:
        mapper: debug
        service: info
        controller: info

shsl:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: shslad
    user-secret-key: shslus
    # 设置jwt过期时间
    admin-ttl: 7200000
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-token-name: authentication

# 指定文件上传位置
photo:
  file:
    dir: C:\Users\清臻雨童\Desktop\DDL\学习\体育馆\CPT202---Super-high-school-level-Sport-Centre\CPT202-SHSLSC\shsl-server\src\main\resources\static\img\store




